# This is a basic workflow to help you get started with Actions

name: Production CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linters:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            lib/*/node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install node modules
        run: |
          npm install

      - name: Check lint
        run: |
          npm run lint:check

  prettier:
    needs: linters
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            lib/*/node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install node modules
        run: |
          npm install

      - name: Check prettier
        run: |
          npm run pretty:check

  types:
    needs: [linters, prettier]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            lib/*/node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install node modules
        run: |
          npm install

      - name: Fix types check
        run: |
          npm run tsc

  test:
    needs: [linters, prettier, types]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            lib/*/node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install node modules
        run: |
          npm install

      - name: Tests
        run: |
          npm run test
